### ISSUE TITLE
Test fails with perl 5.19.x

### ISSUE THREAD

**Issue by eserte** [creaktive/Acme-TLDR#1]
See http://matrix.cpantesters.org/?dist=Acme-TLDR+0.002
It looks like there's a problem with Digest::MD5, which probably should be installed, as it's a core module

**Comment by chorny** [comment]
On 5.18.0 same failure. http://www.cpantesters.org/cpan/report/feb62516-6c02-1014-a064-af71db05e747

**Comment by creaktive** [comment]
Apparently, `ExtUtils::Installed` sometimes fails to list `Digest::MD5` under tester environments.

**Comment by eserte** [comment]
Just a guess: maybe the difference is whether Digest::MD5 is additionally installed in site_perl or not?

**Comment by creaktive** [comment]
Indeed, here's the output for the stock Perl that comes with Mac OS X:

``` sh
Stas-MacBook:~ root# perl -MExtUtils::Installed -E 'say for ExtUtils::Installed->new->modules'
Bundle::NetSNMP
Perl
mod_perl2
```

Will shave dat yak :)
